spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://localhost:3306/erasm_dev?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root
logging.level.com.erasm=DEBUG
logging.level.org.springframework.security=DEBUG
