package com.erasm.controller;
import com.erasm.dto.request.*; import com.erasm.dto.response.*; import com.erasm.service.EmployeeService; import jakarta.validation.Valid; import org.springframework.data.domain.Page; import org.springframework.data.domain.Pageable; import org.springframework.http.*; import org.springframework.security.access.prepost.PreAuthorize; import org.springframework.web.bind.annotation.*; import java.util.List;

@RestController @RequestMapping("/employees") public class EmployeeController {
    private final EmployeeService svc; public EmployeeController(EmployeeService s) { svc=s; }
    @GetMapping @PreAuthorize("hasAnyRole('ADMIN','RESOURCE_MANAGER')") public ResponseEntity<ApiResponse<Page<EmployeeResponse>>> getAll(Pageable p) { return ResponseEntity.ok(ApiResponse.success(svc.getAllEmployees(p))); }
    @GetMapping("/{id}") @PreAuthorize("hasAnyRole('ADMIN','RESOURCE_MANAGER','EMPLOYEE')") public ResponseEntity<ApiResponse<EmployeeResponse>> getById(@PathVariable Long id) { return ResponseEntity.ok(ApiResponse.success(svc.getEmployeeById(id))); }
    @PostMapping @PreAuthorize("hasRole('ADMIN')") public ResponseEntity<ApiResponse<EmployeeResponse>> create(@Valid @RequestBody EmployeeRequest r) { return ResponseEntity.status(HttpStatus.CREATED).body(ApiResponse.success(svc.createEmployee(r))); }
    @PutMapping("/{id}") @PreAuthorize("hasAnyRole('ADMIN','EMPLOYEE')") public ResponseEntity<ApiResponse<EmployeeResponse>> update(@PathVariable Long id, @Valid @RequestBody EmployeeRequest r) { return ResponseEntity.ok(ApiResponse.success(svc.updateEmployee(id,r))); }
    @DeleteMapping("/{id}") @PreAuthorize("hasRole('ADMIN')") public ResponseEntity<ApiResponse<Void>> delete(@PathVariable Long id) { svc.softDeleteEmployee(id); return ResponseEntity.ok(ApiResponse.success("Deleted",null)); }
    @GetMapping("/bench") @PreAuthorize("hasAnyRole('RESOURCE_MANAGER','ADMIN')") public ResponseEntity<ApiResponse<Page<EmployeeResponse>>> bench(Pageable p) { return ResponseEntity.ok(ApiResponse.success(svc.getBenchEmployees(p))); }
    @GetMapping("/search") @PreAuthorize("hasAnyRole('RESOURCE_MANAGER','ADMIN')") public ResponseEntity<ApiResponse<List<EmployeeResponse>>> search(@RequestParam String skill, @RequestParam String level) { return ResponseEntity.ok(ApiResponse.success(svc.searchEmployees(skill,level,true))); }
    @GetMapping("/{id}/skills") public ResponseEntity<ApiResponse<List<EmployeeResponse.EmployeeSkillResponse>>> getSkills(@PathVariable Long id) { return ResponseEntity.ok(ApiResponse.success(svc.getEmployeeSkills(id))); }
    @PostMapping("/{id}/skills") @PreAuthorize("hasAnyRole('EMPLOYEE','ADMIN')") public ResponseEntity<ApiResponse<EmployeeResponse.EmployeeSkillResponse>> addSkill(@PathVariable Long id, @Valid @RequestBody EmployeeSkillRequest r) { return ResponseEntity.status(HttpStatus.CREATED).body(ApiResponse.success(svc.addSkillToEmployee(id,r))); }
    @PutMapping("/{id}/skills/{sid}") @PreAuthorize("hasAnyRole('EMPLOYEE','ADMIN')") public ResponseEntity<ApiResponse<EmployeeResponse.EmployeeSkillResponse>> updateSkill(@PathVariable Long id, @PathVariable Long sid, @Valid @RequestBody EmployeeSkillRequest r) { return ResponseEntity.ok(ApiResponse.success(svc.updateEmployeeSkill(id,sid,r))); }
    @DeleteMapping("/{id}/skills/{sid}") @PreAuthorize("hasAnyRole('EMPLOYEE','ADMIN')") public ResponseEntity<ApiResponse<Void>> removeSkill(@PathVariable Long id, @PathVariable Long sid) { svc.removeSkillFromEmployee(id,sid); return ResponseEntity.ok(ApiResponse.success("Removed",null)); }
    @GetMapping("/{id}/certifications") public ResponseEntity<ApiResponse<List<EmployeeResponse.CertificationResponse>>> getCerts(@PathVariable Long id) { return ResponseEntity.ok(ApiResponse.success(svc.getEmployeeCertifications(id))); }
    @PostMapping("/{id}/certifications") @PreAuthorize("hasAnyRole('EMPLOYEE','ADMIN')") public ResponseEntity<ApiResponse<EmployeeResponse.CertificationResponse>> addCert(@PathVariable Long id, @Valid @RequestBody CertificationRequest r) { return ResponseEntity.status(HttpStatus.CREATED).body(ApiResponse.success(svc.addCertification(id,r))); }
    @PutMapping("/{id}/certifications/{cid}") @PreAuthorize("hasAnyRole('EMPLOYEE','ADMIN')") public ResponseEntity<ApiResponse<EmployeeResponse.CertificationResponse>> updateCert(@PathVariable Long id, @PathVariable Long cid, @Valid @RequestBody CertificationRequest r) { return ResponseEntity.ok(ApiResponse.success(svc.updateCertification(id,cid,r))); }
    @DeleteMapping("/{id}/certifications/{cid}") @PreAuthorize("hasAnyRole('EMPLOYEE','ADMIN')") public ResponseEntity<ApiResponse<Void>> delCert(@PathVariable Long id, @PathVariable Long cid) { svc.deleteCertification(id,cid); return ResponseEntity.ok(ApiResponse.success("Deleted",null)); }
}
