package com.erasm.controller;
import com.erasm.dto.request.ResourceRequestDto; import com.erasm.dto.response.ApiResponse; import com.erasm.entity.ResourceRequest; import com.erasm.enums.RequestStatus; import com.erasm.service.ResourceRequestService; import jakarta.validation.Valid; import org.springframework.data.domain.Page; import org.springframework.data.domain.Pageable; import org.springframework.http.*; import org.springframework.security.access.prepost.PreAuthorize; import org.springframework.security.core.Authentication; import org.springframework.web.bind.annotation.*; import java.util.Map;

@RestController @RequestMapping("/resource-requests") public class ResourceRequestController {
    private final ResourceRequestService svc; public ResourceRequestController(ResourceRequestService s) { svc=s; }
    @GetMapping @PreAuthorize("hasAnyRole('DELIVERY_MANAGER','RESOURCE_MANAGER','ADMIN')") public ResponseEntity<ApiResponse<Page<ResourceRequest>>> getAll(@RequestParam(required=false) RequestStatus status, Pageable p) { return ResponseEntity.ok(ApiResponse.success(svc.getAllRequests(status,p))); }
    @GetMapping("/{id}") @PreAuthorize("hasAnyRole('DELIVERY_MANAGER','RESOURCE_MANAGER','ADMIN')") public ResponseEntity<ApiResponse<ResourceRequest>> getById(@PathVariable Long id) { return ResponseEntity.ok(ApiResponse.success(svc.getRequestById(id))); }
    @PostMapping @PreAuthorize("hasRole('DELIVERY_MANAGER')") public ResponseEntity<ApiResponse<ResourceRequest>> create(@Valid @RequestBody ResourceRequestDto d, Authentication a) { return ResponseEntity.status(HttpStatus.CREATED).body(ApiResponse.success(svc.createRequest(d,a.getName()))); }
    @PutMapping("/{id}") @PreAuthorize("hasRole('DELIVERY_MANAGER')") public ResponseEntity<ApiResponse<ResourceRequest>> update(@PathVariable Long id, @Valid @RequestBody ResourceRequestDto d) { return ResponseEntity.ok(ApiResponse.success(svc.updateRequest(id,d))); }
    @DeleteMapping("/{id}") @PreAuthorize("hasRole('DELIVERY_MANAGER')") public ResponseEntity<ApiResponse<Void>> delete(@PathVariable Long id) { svc.deleteRequest(id); return ResponseEntity.ok(ApiResponse.success("Deleted",null)); }
    @PutMapping("/{id}/submit") @PreAuthorize("hasRole('DELIVERY_MANAGER')") public ResponseEntity<ApiResponse<ResourceRequest>> submit(@PathVariable Long id) { return ResponseEntity.ok(ApiResponse.success(svc.submitRequest(id))); }
    @PutMapping("/{id}/approve") @PreAuthorize("hasRole('RESOURCE_MANAGER')") public ResponseEntity<ApiResponse<ResourceRequest>> approve(@PathVariable Long id, Authentication a) { return ResponseEntity.ok(ApiResponse.success(svc.approveRequest(id,a.getName()))); }
    @PutMapping("/{id}/reject") @PreAuthorize("hasRole('RESOURCE_MANAGER')") public ResponseEntity<ApiResponse<ResourceRequest>> reject(@PathVariable Long id, @RequestBody Map<String,String> b, Authentication a) { return ResponseEntity.ok(ApiResponse.success(svc.rejectRequest(id,b.get("remarks"),a.getName()))); }
}
