package com.erasm.service;
import com.erasm.dto.request.*; import com.erasm.dto.response.EmployeeResponse; import com.erasm.entity.*; import com.erasm.exception.*; import com.erasm.mapper.EmployeeMapper; import com.erasm.repository.*; import com.erasm.util.AuditUtil; import org.springframework.data.domain.Page; import org.springframework.data.domain.Pageable; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.time.LocalDate; import java.util.List; import java.util.stream.Collectors;

@Service public class EmployeeService {
    private final EmployeeRepository empRepo; private final UserRepository userRepo; private final SkillRepository skillRepo; private final EmployeeSkillRepository esRepo; private final CertificationRepository certRepo; private final EmployeeMapper mapper; private final AuditService audit; private final AuditUtil auditUtil;
    public EmployeeService(EmployeeRepository e, UserRepository u, SkillRepository s, EmployeeSkillRepository es, CertificationRepository c, EmployeeMapper m, AuditService a, AuditUtil au) { empRepo=e; userRepo=u; skillRepo=s; esRepo=es; certRepo=c; mapper=m; audit=a; auditUtil=au; }

    public Page<EmployeeResponse> getAllEmployees(Pageable p) { return empRepo.findAll(p).map(mapper::toResponse); }
    public EmployeeResponse getEmployeeById(Long id) { return mapper.toResponse(empRepo.findById(id).orElseThrow(() -> new EmployeeNotFoundException("Employee not found: " + id))); }

    @Transactional public EmployeeResponse createEmployee(EmployeeRequest r) {
        User u = userRepo.findById(r.getUserId()).orElseThrow(() -> new UserNotFoundException("User not found: " + r.getUserId()));
        if (empRepo.existsByUserId(r.getUserId())) throw new DuplicateResourceException("Employee exists for user: " + r.getUserId());
        Employee e = empRepo.save(Employee.builder().user(u).firstName(r.getFirstName()).lastName(r.getLastName()).phone(r.getPhone()).department(r.getDepartment()).designation(r.getDesignation()).dateOfJoining(r.getDateOfJoining()).employmentType(r.getEmploymentType()).totalExperienceYears(r.getTotalExperienceYears()!=null?r.getTotalExperienceYears():0.0).benchStatus(true).build());
        audit.log("EMPLOYEE",e.getId(),"CREATE",auditUtil.getCurrentUserEmail(),"Created: "+e.getFirstName()); return mapper.toResponse(e);
    }
    @Transactional public EmployeeResponse updateEmployee(Long id, EmployeeRequest r) { Employee e = empRepo.findById(id).orElseThrow(() -> new EmployeeNotFoundException("Employee not found: " + id)); mapper.updateEntity(e,r); e = empRepo.save(e); audit.log("EMPLOYEE",id,"UPDATE",auditUtil.getCurrentUserEmail(),"Updated"); return mapper.toResponse(e); }
    @Transactional public void softDeleteEmployee(Long id) { Employee e = empRepo.findById(id).orElseThrow(() -> new EmployeeNotFoundException("Not found")); e.getUser().setIsActive(false); userRepo.save(e.getUser()); audit.log("EMPLOYEE",id,"DELETE",auditUtil.getCurrentUserEmail(),"Soft-deleted"); }
    public Page<EmployeeResponse> getBenchEmployees(Pageable p) { return empRepo.findByBenchStatusTrue(p).map(mapper::toResponse); }
    public List<EmployeeResponse> searchEmployees(String skill, String level, Boolean bench) { return empRepo.findBySkillAndLevelAndAvailable(skill, level).stream().map(mapper::toResponse).collect(Collectors.toList()); }

    // Skills
    public List<EmployeeResponse.EmployeeSkillResponse> getEmployeeSkills(Long eid) { empRepo.findById(eid).orElseThrow(() -> new EmployeeNotFoundException("Not found")); return esRepo.findByEmployeeId(eid).stream().map(es -> EmployeeResponse.EmployeeSkillResponse.builder().id(es.getId()).skillId(es.getSkill().getId()).skillName(es.getSkill().getName()).category(es.getSkill().getCategory()).level(es.getLevel().name()).yearsOfExperience(es.getYearsOfExperience()).lastUsedDate(es.getLastUsedDate()).build()).collect(Collectors.toList()); }
    @Transactional public EmployeeResponse.EmployeeSkillResponse addSkillToEmployee(Long eid, EmployeeSkillRequest r) { Employee e = empRepo.findById(eid).orElseThrow(() -> new EmployeeNotFoundException("Not found")); Skill s = skillRepo.findById(r.getSkillId()).orElseThrow(() -> new SkillNotFoundException("Not found")); if (esRepo.existsByEmployeeIdAndSkillId(eid,r.getSkillId())) throw new DuplicateResourceException("Already has skill"); EmployeeSkill es = esRepo.save(EmployeeSkill.builder().employee(e).skill(s).level(r.getLevel()).yearsOfExperience(r.getYearsOfExperience()!=null?r.getYearsOfExperience():0.0).lastUsedDate(r.getLastUsedDate()).build()); audit.log("EMPLOYEE_SKILL",es.getId(),"CREATE",auditUtil.getCurrentUserEmail(),"Skill added"); return EmployeeResponse.EmployeeSkillResponse.builder().id(es.getId()).skillId(s.getId()).skillName(s.getName()).category(s.getCategory()).level(es.getLevel().name()).yearsOfExperience(es.getYearsOfExperience()).lastUsedDate(es.getLastUsedDate()).build(); }
    @Transactional public EmployeeResponse.EmployeeSkillResponse updateEmployeeSkill(Long eid, Long sid, EmployeeSkillRequest r) { EmployeeSkill es = esRepo.findByEmployeeIdAndSkillId(eid,sid).orElseThrow(() -> new SkillNotFoundException("Not found")); es.setLevel(r.getLevel()); if(r.getYearsOfExperience()!=null) es.setYearsOfExperience(r.getYearsOfExperience()); if(r.getLastUsedDate()!=null) es.setLastUsedDate(r.getLastUsedDate()); es = esRepo.save(es); return EmployeeResponse.EmployeeSkillResponse.builder().id(es.getId()).skillId(es.getSkill().getId()).skillName(es.getSkill().getName()).category(es.getSkill().getCategory()).level(es.getLevel().name()).yearsOfExperience(es.getYearsOfExperience()).lastUsedDate(es.getLastUsedDate()).build(); }
    @Transactional public void removeSkillFromEmployee(Long eid, Long sid) { EmployeeSkill es = esRepo.findByEmployeeIdAndSkillId(eid,sid).orElseThrow(() -> new SkillNotFoundException("Not found")); esRepo.delete(es); }

    // Certifications
    public List<EmployeeResponse.CertificationResponse> getEmployeeCertifications(Long eid) { empRepo.findById(eid).orElseThrow(() -> new EmployeeNotFoundException("Not found")); return certRepo.findByEmployeeId(eid).stream().map(c -> EmployeeResponse.CertificationResponse.builder().id(c.getId()).name(c.getName()).issuingOrganization(c.getIssuingOrganization()).issueDate(c.getIssueDate()).expiryDate(c.getExpiryDate()).credentialId(c.getCredentialId()).credentialUrl(c.getCredentialUrl()).isExpired(c.getExpiryDate()!=null&&c.getExpiryDate().isBefore(LocalDate.now())).build()).collect(Collectors.toList()); }
    @Transactional public EmployeeResponse.CertificationResponse addCertification(Long eid, CertificationRequest r) { Employee e = empRepo.findById(eid).orElseThrow(() -> new EmployeeNotFoundException("Not found")); Certification c = certRepo.save(Certification.builder().employee(e).name(r.getName()).issuingOrganization(r.getIssuingOrganization()).issueDate(r.getIssueDate()).expiryDate(r.getExpiryDate()).credentialId(r.getCredentialId()).credentialUrl(r.getCredentialUrl()).build()); boolean exp = c.getExpiryDate()!=null&&c.getExpiryDate().isBefore(LocalDate.now()); return EmployeeResponse.CertificationResponse.builder().id(c.getId()).name(c.getName()).issuingOrganization(c.getIssuingOrganization()).issueDate(c.getIssueDate()).expiryDate(c.getExpiryDate()).credentialId(c.getCredentialId()).credentialUrl(c.getCredentialUrl()).isExpired(exp).build(); }
    @Transactional public EmployeeResponse.CertificationResponse updateCertification(Long eid, Long cid, CertificationRequest r) { Certification c = certRepo.findById(cid).orElseThrow(() -> new SkillNotFoundException("Cert not found")); if(!c.getEmployee().getId().equals(eid)) throw new AllocationException("Cert not owned"); if(r.getName()!=null) c.setName(r.getName()); if(r.getIssuingOrganization()!=null) c.setIssuingOrganization(r.getIssuingOrganization()); if(r.getIssueDate()!=null) c.setIssueDate(r.getIssueDate()); if(r.getExpiryDate()!=null) c.setExpiryDate(r.getExpiryDate()); if(r.getCredentialId()!=null) c.setCredentialId(r.getCredentialId()); if(r.getCredentialUrl()!=null) c.setCredentialUrl(r.getCredentialUrl()); c = certRepo.save(c); return EmployeeResponse.CertificationResponse.builder().id(c.getId()).name(c.getName()).issuingOrganization(c.getIssuingOrganization()).issueDate(c.getIssueDate()).expiryDate(c.getExpiryDate()).credentialId(c.getCredentialId()).credentialUrl(c.getCredentialUrl()).isExpired(c.getExpiryDate()!=null&&c.getExpiryDate().isBefore(LocalDate.now())).build(); }
    @Transactional public void deleteCertification(Long eid, Long cid) { Certification c = certRepo.findById(cid).orElseThrow(() -> new SkillNotFoundException("Not found")); if(!c.getEmployee().getId().equals(eid)) throw new AllocationException("Not owned"); certRepo.delete(c); }
}
