package com.erasm.service;
import com.erasm.dto.response.UserResponse; import com.erasm.entity.*; import com.erasm.exception.UserNotFoundException; import com.erasm.mapper.UserMapper; import com.erasm.repository.*; import com.erasm.util.AuditUtil; import org.springframework.data.domain.Page; import org.springframework.data.domain.Pageable; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;

@Service public class UserService {
    private final UserRepository userRepo; private final RoleRepository roleRepo; private final UserMapper mapper; private final AuditService audit; private final AuditUtil auditUtil;
    public UserService(UserRepository u, RoleRepository r, UserMapper m, AuditService a, AuditUtil au) { userRepo=u; roleRepo=r; mapper=m; audit=a; auditUtil=au; }
    public Page<UserResponse> getAllUsers(Pageable p) { return userRepo.findAll(p).map(mapper::toResponse); }
    public UserResponse getUserById(Long id) { return mapper.toResponse(userRepo.findById(id).orElseThrow(() -> new UserNotFoundException("User not found: " + id))); }
    @Transactional public UserResponse updateUser(Long id, String email, String roleName) { User u = userRepo.findById(id).orElseThrow(() -> new UserNotFoundException("User not found: " + id)); if (email!=null) u.setEmail(email.toLowerCase().trim()); if (roleName!=null) u.setRole(roleRepo.findByName(roleName.toUpperCase()).orElseThrow(() -> new IllegalArgumentException("Invalid role"))); u = userRepo.save(u); audit.log("USER",id,"UPDATE",auditUtil.getCurrentUserEmail(),"User updated"); return mapper.toResponse(u); }
    @Transactional public void softDeleteUser(Long id) { User u = userRepo.findById(id).orElseThrow(() -> new UserNotFoundException("User not found: " + id)); u.setIsActive(false); userRepo.save(u); audit.log("USER",id,"DELETE",auditUtil.getCurrentUserEmail(),"User soft-deleted"); }
    @Transactional public UserResponse assignRole(Long id, String r) { User u = userRepo.findById(id).orElseThrow(() -> new UserNotFoundException("User not found")); u.setRole(roleRepo.findByName(r.toUpperCase()).orElseThrow(() -> new IllegalArgumentException("Invalid role"))); u = userRepo.save(u); audit.log("USER",id,"UPDATE",auditUtil.getCurrentUserEmail(),"Role assigned: "+r); return mapper.toResponse(u); }
    @Transactional public UserResponse activateUser(Long id) { User u = userRepo.findById(id).orElseThrow(() -> new UserNotFoundException("User not found")); u.setIsActive(true); u.setAccountLocked(false); u.setFailedLoginAttempts(0); u.setLockedAt(null); u = userRepo.save(u); audit.log("USER",id,"UPDATE",auditUtil.getCurrentUserEmail(),"Activated"); return mapper.toResponse(u); }
    @Transactional public UserResponse deactivateUser(Long id) { User u = userRepo.findById(id).orElseThrow(() -> new UserNotFoundException("User not found")); u.setIsActive(false); u = userRepo.save(u); audit.log("USER",id,"UPDATE",auditUtil.getCurrentUserEmail(),"Deactivated"); return mapper.toResponse(u); }
}
